version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: todolist-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todolistdb
      MYSQL_USER: todouser
      MYSQL_PASSWORD: Tharu12
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - todolist-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Spring Boot Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: todolist-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/todolistdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: todouser
      SPRING_DATASOURCE_PASSWORD: Tharu12
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      APP_JWT_SECRET: yourSuperSecretKeyShouldBeAtLeast32CharsLong
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - todolist-network

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: todolist-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - todolist-network

networks:
  todolist-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
